name: pro_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  http: ^1.2.2
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  dart_jsonwebtoken: ^2.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/rooms/
    - assets/icon2/
    - assets/user/
