name: pro_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # ใช้สำหรับการทำ HTTP request
  http: ^1.2.2  # อัปเดตเป็นเวอร์ชันที่แนะนำ

  # ใช้สำหรับการจัดการสถานะ (ถ้าจำเป็น)
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # ถ้าคุณมี assets หรือ custom fonts สามารถเพิ่มได้ที่นี่
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
